version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-card-bot
    restart: unless-stopped
    environment:
      - TOKEN="8475923416:AAEn7pC6C6OsM57RU1HDOjQTdc1pa0CF4_o"
      - CHANNEL_ID=-1002195866325
    env_file:
      - .env
    volumes:
      - bot-data:/home/botuser/data
      - ./data:/app/data:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-data:
    driver: local